# A TOML linter such as https://tombi-toml.github.io/tombi/ can use this schema
# to validate your config. If you encounter any issues, please make an issue at
# https://github.com/yazi-rs/schemas.
#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]

prepend_keymap = [
  # Seeking
  { on = "K", run = "seek -10", desc = "Seek up 10 units in the preview" },
  { on = "J", run = "seek 10",  desc = "Seek down 10 units in the preview" },
]
