# A TOML linter such as https://tombi-toml.github.io/tombi/ can use this schema
# to validate your config. If you encounter any issues, please make an issue at
# https://github.com/yazi-rs/schemas.
#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
sort_by        = "natural"
title_format   = "Yazi: {cwd}"

[preview]
max_width       = 800
max_height      = 1200
